server:
  port: 8769
spring:
  application:
      name: eureka-server
eureka:
  instance:
    hostname: eureka-server-peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/
